version: "3.*"
services:
    beersexampleapp:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: 'www-data'
        image: beersexampleapp
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - 80:8000
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: 'www-data'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
        command: ["sh", "-c", "php artisan migrate --force && php artisan db:seed --force || sleep 10"]
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u ${DB_USERNAME} -p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            mysql:
                condition: service_healthy
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT:=3306
        networks:
            - sail
        ports:
            - 8081:80
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
